#!/usr/bin/env sh
# Give a linked checkout its own cargo target dir, seeded from the main one, so
# its first build is seconds instead of a ~4 GiB cold build.
#
# Checkouts must not *share* a target dir. Cargo gives workspace-local crates a
# path-independent `-C metadata` hash, so every checkout writes the same
# `deps/libodm_render-<hash>.rlib` and the same `.fingerprint/` entry; freshness
# then comes down to source mtime, and a checkout whose sources predate a peer's
# last build is judged fresh and silently links the peer's code.
#
# Seeding buys the same warm start without the shared mutable state:
#   deps/       hardlinked — rustc replaces artifacts (unlink + create), so a
#                            rebuild here never writes through to the peer
#   .fingerprint/, build/, gn_out/
#               copied     — cargo *does* rewrite these in place, and
#                            build/*/output records absolute paths into the
#                            target dir (rewritten below to point here)
#   crates/*    skipped    — this checkout compiles its own
#
# Costs ~700 MiB per checkout; the 5.7 GiB of deps/ is free. Idempotent, and a
# no-op in the main checkout, outside a git repo, or once target/ exists.
set -eu

command -v git >/dev/null 2>&1 || exit 0
top=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
common=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || exit 0

# Linked checkouts have a .git *file*; the common dir belongs to the main clone.
[ "$(basename "$common")" = ".git" ] || exit 0   # bare repo: no main checkout
main=$(dirname "$common")
[ "$top" != "$main" ] || exit 0                  # we *are* the main checkout

# Retire the config written by the old shared-target scheme.
config="$top/.cargo/config.toml"
if [ -f "$config" ] && grep -q 'Generated by scripts/' "$config" 2>/dev/null; then
  rm -f "$config"
  rmdir "$top/.cargo" 2>/dev/null || true
  echo "seed-target: dropped $config (checkouts no longer share a target dir)"
fi

[ ! -e "$top/target" ] || exit 0                 # already seeded, or built
[ -d "$main/target" ] || exit 0                  # nothing to seed from

tmp="$top/.target-seed.$$"
trap 'rm -rf "$tmp"' EXIT INT TERM
rm -rf "$tmp"
cp -al "$main/target" "$tmp" 2>/dev/null || {
  echo "seed-target: can't hardlink from $main/target (different filesystem?)" >&2
  exit 0
}

locals=""
for d in "$top"/crates/*/; do
  [ -d "$d" ] || continue
  n=${d%/}
  locals="$locals ${n##*/}"
done

for prof in "$tmp"/*/; do
  [ -d "$prof" ] || continue

  # Uplifted workspace artifacts (bins, rlibs, .d) are the only files directly
  # in a profile dir. incremental/ is a recompile accelerator, not an input.
  find "$prof" -maxdepth 1 -type f -delete
  rm -rf "$prof/incremental" "$prof/examples"

  # Local crates: what this checkout will build, and exactly what would collide.
  for c in $locals; do
    u=$(printf '%s' "$c" | tr - _)
    rm -rf "$prof/deps/$c"-* "$prof/deps/$u"-* "$prof/deps/lib$u"-* \
           "$prof/.fingerprint/$c"-* "$prof/build/$c"-*
  done
  # Integration-test binaries are named after the test *file* (report-<hash>),
  # so the per-crate purge misses them. Every extensionless file in deps/ is a
  # workspace executable (external deps only produce .rlib/.rmeta/.so/.d).
  find "$prof/deps" -maxdepth 1 -type f ! -name '*.*' -delete 2>/dev/null || true

  # Break the hardlinks on everything cargo rewrites in place.
  for d in .fingerprint build gn_out; do
    [ -d "$prof/$d" ] || continue
    mv "$prof/$d" "$prof/$d.seeding"
    cp -a --reflink=auto "$prof/$d.seeding" "$prof/$d"
    rm -rf "$prof/$d.seeding"
  done

  # rustc's make-style dep files: nothing reads them (cargo keeps its own copy
  # under .fingerprint/) and the seeded ones name the wrong target dir.
  find "$prof/deps" -maxdepth 1 -name '*.d' -delete 2>/dev/null || true
done

# Build scripts record absolute paths into the target dir they ran under. Only
# touch the files that actually name it, and keep their mtimes: cargo compares a
# build script's output mtime against its consumers', so a gratuitous rewrite
# marks every crate with a build script stale.
for f in "$tmp"/*/build/*/output "$tmp"/*/build/*/root-output; do
  [ -f "$f" ] || continue
  grep -q "$main/target" "$f" 2>/dev/null || continue
  sed -i "s|$main/target|$top/target|g" "$f"
  ref="$main/target${f#"$tmp"}"
  if [ -f "$ref" ]; then touch -r "$ref" "$f"; fi
done

mv -T "$tmp" "$top/target" 2>/dev/null || exit 0  # lost a race; the peer won
trap - EXIT INT TERM
echo "seed-target: seeded $top/target from $main/target"
