#!/usr/bin/env sh
# Point this git worktree's cargo target dir at the main checkout's.
#
# Cargo keys dependency artifacts by package+features+profile+rustc, not by
# workspace path, so worktrees can share one target dir: all ~950 deps, the
# prebuilt librusty_v8.a, and the manifold/TBB C++ build get reused, and only
# the handful of local crates rebuild. A fresh worktree then builds in seconds
# and costs ~no disk instead of ~4 GiB.
#
# Idempotent; safe to run from anywhere in the repo. No-op in the main checkout
# (its default target/ *is* the shared one) and outside a git repo.
set -eu

command -v git >/dev/null 2>&1 || exit 0
top=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
common=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || exit 0

# Linked worktrees have a .git *file*; the common dir belongs to the main clone.
[ "$(basename "$common")" = ".git" ] || exit 0   # bare repo: no main worktree
main=$(dirname "$common")
[ "$top" != "$main" ] || exit 0                  # we *are* the main checkout

config="$top/.cargo/config.toml"
new=$(cat <<EOF
# Generated by scripts/shared-target.sh — see notes/build-environment.md.
# Share the main checkout's build cache instead of rebuilding ~950 deps here.
[build]
target-dir = "$main/target"
EOF
)

if [ -f "$config" ] && [ "$(cat "$config")" = "$new" ]; then
  exit 0
fi
if [ -f "$config" ] && ! grep -q "Generated by scripts/shared-target.sh" "$config"; then
  echo "shared-target: $config exists and wasn't generated by us; leaving it alone" >&2
  exit 0
fi
mkdir -p "$top/.cargo"
printf '%s\n' "$new" > "$config"
echo "shared-target: $top now builds into $main/target"
